{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ultimate-k8s-toolbox.serviceAccountName" . }}
  namespace: {{ include "ultimate-k8s-toolbox.namespace" . }}
  labels:
    {{- include "ultimate-k8s-toolbox.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
